import {
  Wifi,
  Snowflake,
  Tv,
  ShieldCheck,
  Sparkles,
  Coffee,
  MapPinned,
  Camera,
  WashingMachine,
  Refrigerator,
  Briefcase,
  Key,
  ShowerHead,
} from "lucide-react";
import { FaElevator } from "react-icons/fa6";

export const roomTypes = [
  "Standard Single",
  "Deluxe Single",
  "Standard Twin",
  "Standard Double",
  "Deluxe Double A (Bottle)",
  "Deluxe Double B (Car)",
  "Deluxe Double C (Jackson Pollock)",
  "Deluxe Double D (Slum)",
  "Deluxe Double E (Circle)",
  "Deluxe Double F",
  "Bunks for 4",
  "Mix Dorm Room",
  "Bunks for 6",
  "Bed for 2",
  "Executive Suite",
];

export const amenitiesList = [
  { id: "wifi", name: "Free Wi-Fi", icon: Wifi },
  { id: "ac", name: "Air Conditioning", icon: Snowflake },
  { id: "tv", name: "Smart TV", icon: Tv },
  { id: "frontdesk", name: "24-Hour Front Desk", icon: ShieldCheck },
  { id: "cctv", name: "CCTV Surveillance", icon: Camera },
  { id: "housekeeping", name: "Daily Housekeeping", icon: Sparkles },
  { id: "coffee", name: "Coffee Corner", icon: Coffee },
  { id: "laundry", name: "Laundry Vending Machine", icon: WashingMachine },
  { id: "fridge", name: "Mini Fridge", icon: Refrigerator },
  { id: "meeting", name: "Meeting Work Place", icon: Briefcase },
  { id: "keycard", name: "Key Card Access", icon: Key },
  { id: "shower", name: "Hot & Cold Shower", icon: ShowerHead },
  { id: "lift", name: "Lift Access", icon: FaElevator },
  { id: "tour", name: "Tour Assistance", icon: MapPinned }, 
];
